package_assets: off
javascripts:
  app:
    - public/javascripts/jquery-1.4.4.min.js
    - public/javascripts/json2.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/application.js
    - public/javascripts/jquery.dotimeout.js
    - public/javascripts/**/*.js

stylesheets:
  app:
    - public/stylesheets/reset.css
    - public/stylesheets/*.css